### ISSUE TITLE
Possible regression with docker-machine 0.5.0? Starting already existing vm does not work.

### ISSUE THREAD

**Issue by wongak** [ory-am/dockertest#15]
I'm not exactly sure what the circumstances are, but when I run the following:

    $ docker-machine start default
    Machine "default" is already running.
    echo $?
    1

docker-machine returns an error code. After skimming the dockertest code, I noticed that ```startDockerMachine()``` would always return ```false``` for the exit-code 1. It would also always be called.

Am I correct with my assumptions?

I thought of 2 different ways to tackle this issue:

* Give preference to the ```docker``` command in ```runLongTest()```. This would allow a correctly set up environment to run directly against the ```docker``` command, even if ```docker-machine``` is present.
* Remove the initial ```DockerMachineAvailable = false``` inside ```runLongTest()``` and only start the docker machine if ```DockerMachineAvailable``` is false and ```haveDockerMachine```. This would allow the tests to force docker machines to not be recreated.

Cheers

**Comment by arekkas** [comment]
Oh, this looks indeed like a regression issue. There are multiple things broken, I will check into it. I think this should fix the issue you described:

```

	DockerMachineAvailable = false
	if haveDockerMachine() {
		DockerMachineAvailable = true
		if startDockerMachine() {
			return errors.New("Docker machine image seems to be running.")
		}
	} else if !haveDocker() {
		return errors.New("Neither 'docker' nor 'docker-machine' available on this system.")
	}
```

`docker` and `docker-machine` will never be available on the same machine, because docker only runs on linux and docker-machine is only available on windows and mac.

**Comment by arekkas** [comment]
Hm docker-machine looks sorta borken. When running the Docker Quickstart Terminal I get: *Error creating machine: Error in driver during machine creation: exit status1*

**Comment by wongak** [comment]
Thank you. I would still suggest to give the set environment vars and the ```docker``` command preference.

This would be in line with how docker and all their tools work.

This way you could point dockertest to the selected machines without having to maintain additional configs.
