### ISSUE TITLE
Ability to specify database version

### ISSUE THREAD

**Issue by Taik** [ory-am/dockertest#22]
First, thanks for this. It is definitely useful!

How hard would it be to add version support to this? Ideally I'd like to run unit/integration tests using the same version of MySQL/Redis/PQ/etc. as the version in production.

**Comment by arekkas** [comment]
Right now, docker is for example [used here](https://github.com/ory-am/dockertest/blob/master/docker.go#L262). You would basically have to add the command to specify the version. It shouldn't be too hard, so why not give it a try yourself? :)

**Comment by Taik** [comment]
Perfect, thanks for pointing me to that. That definitely works for me!
