### ISSUE TITLE
Expose setupContainer

### ISSUE THREAD

**Issue by Taik** [ory-am/dockertest#24]
Was there any explicit reason as to why setupContainer is private and not public? I'd like to use this to spin up some private images for testing without having to manage my fork of dockertest.

Thanks again for the awesome package.

**Comment by arekkas** [comment]
good idea, i will adress this in #23

**Comment by Taik** [comment]
Thanks for the quick turn-around! It seems that I also need https://github.com/ory-am/dockertest/blob/master/docker.go#L97 to be public (it gets called in the `start()` function).

**Comment by arekkas** [comment]
feel free to open a pr with what you need
