### ISSUE TITLE
Mistakes in Readme

### ISSUE THREAD

**Issue by Kaign** [ory-am/dockertest#30]
in **Start a container** section
`db, err := mgo.Dial(url)`
here `db` should be a global variable. Also line
 `return db.Ping() != nil`
should be changed to `return db.Ping() == nil`

**Comment by arekkas** [comment]
Thanks for the hint, can you create a PR?

**Comment by Kaign** [comment]
Sure, here we go..
by the way, thanks, it is very convinient package

**Comment by arekkas** [comment]
Glad you like it :) Thanks for the PR
