### ISSUE TITLE
[mysql] allow to use a customized database instead of default one

### ISSUE THREAD

**Issue by hsinhoyeh** [ory-am/dockertest#33]
hi,

thanks for creating such great tool. It is really saved lots of time to do integration test.
However, we found that you use default "mysql" database (it also called mysql) as your default database.
https://github.com/ory-am/dockertest/blob/master/mysql.go#L35
```
url := fmt.Sprintf("%s:%s@tcp(%s:%d)/mysql", MySQLUsername, MySQLPassword, ip, port)
```
As you may knew, mysql stored user's information and privileges into that database as well. 
That would be an issue if we share the same table names.
I think it is better to let caller decide which one of databases should be used.
And, when mysql container is up, we can create the database if it is not default one.

Let me know your concerns.
If you accept PR, I can send one.

**Comment by arekkas** [comment]
Love that! We should do the same for postgres!
