### ISSUE TITLE
Some suggestions and an alternative to Dockertest

### ISSUE THREAD

**Issue by ibrt** [ory-am/dockertest#35]
Hi Aeneas, I'm opening an issue in absence of other ways to contact you :) I just wanted to let you know I have been working on an alternative approach to achieve the same function of this library, and published it at: https://github.com/ibrt/go-compose. I believe this approach is simpler and has few advantages (listed below), maybe it could be interesting for you to have a look and possibly borrow some ideas!

- It uses a Docker Compose config, which is standard and supports all Docker options
- It is smaller but actually more flexible
- It pulls in way less dependencies
- It completely delegates the Docker environment configuration to whoever runs the tests
- It results in less Go code to start/stop containers (i.e. one call to start and one call to kill everything)

On the downside, it doesn't have any support for standard or predefined services. I am planning to add them in separate subpackages, so callers can actually import only the dependencies they need.

Best,
Ivan

**Comment by ibrt** [comment]
Another small detail, rather than randomly picking a port with a PRNG, it can let Docker do it for you (which means there is no risk of collisions).

**Comment by arekkas** [comment]
Hey looks cool! I like your idea of using docker compose to set up the environment. Really merges "production" and "testing" stages.

How do you get a [container instance](https://godoc.org/github.com/ibrt/go-compose/compose#Container)? Didn't find it in the tests / docs. Also would go-compose work with go-dockerclient as suggested in #11 ?

**Comment by ibrt** [comment]
The Compose type has a Containers map in it, keys are container names, and
values are the corresponding container instances.

IIUC go-dockerclient doesn't support docker compose, which is why I didn't
use it :)

**Comment by arekkas** [comment]
@sbani will take a look at this :)

**Comment by arekkas** [comment]
this will work with https://github.com/ory-am/dockertest/pull/46
