### ISSUE TITLE
Container unreachable 

### ISSUE THREAD

**Issue by miko-code** [ory-am/dockertest#36]
Hi ,
Im trying to run some tests and containers but i getting this error for all the db`s that i tried to run ...

Im running  the mongo  example  and the error is 

`Could not connect to database: Could not set up MongoDB container: 172.17.0.2:36125 unreachable for 10s.`
Test are also producing  this error 
```
  `go test docker_integration_test.go  --run TestConnectToMongoDB
--- FAIL: TestConnectToMongoDB (10.93s)
        Error Trace:    docker_integration_test.go:130
	Error:		Expected nil, but got: &errors.errorString{s:"Could not set up MongoDB container: 172.17.0.2:36126 unreachable for 10s"}
		
FAIL
FAIL	command-line-arguments	10.938s
`
```

**Comment by arekkas** [comment]
Are you running the tests on travis? If yes, check [this](https://github.com/ory-am/dockertest#setting-up-travis-ci). Otherwise it may well be your network configuration which causes troubles. I suggest to check the docker toolbox / docker docs on port forwarding / port publishing.

**Comment by miko-code** [comment]
Im running it on linux  ,
and im ruining this code 
`https://github.com/ory-am/dockertest#start-a-container`

what im doing wrong ?

**Comment by arekkas** [comment]
Sorry, but I do not know your environment. From what I see you're doing everything right but as I said before it might be an issue with your network. You should try running a docker container manually, publish it's port and see if you can connect to it.

Another option would be to set the environment variable `DOCKERTEST_BIND_LOCALHOST=true`

**Comment by miko-code** [comment]
this line did the trick 
```
`	dockertest.BindDockerToLocalhost = "127.0.0.1"
`
```

thanks

**Comment by arekkas** [comment]
You're welcome, I'm glad it worked out :)
