### ISSUE TITLE
import path

### ISSUE THREAD

**Issue by hsinhoyeh** [ory-am/dockertest#40]
hi, does it is intent to do so or mistake?
https://github.com/ory-am/dockertest/blob/d19a39062e37826665d14ab003714308f9c1f3d0/docker_integration_test.go#L15

when we use a versioned package (like gopkg.in/ory-am/dockertest.v2), we won't expect this actually.

**Comment by arekkas** [comment]
good point

**Comment by arekkas** [comment]
feel free to create a PR
