### ISSUE TITLE
API v3

### ISSUE THREAD

**Issue by rawler** [ory-am/dockertest#45]
- Should use `docker inspect` to let docker allocate a bound port
- Should avoid encouraging callbacks and globals in _using code_
- Should allow pluggable runner-types (including implementing in _using code_)
- Should allow pluggable container-types (including implementing in _using code_)

Something in the line of:

```go
type Container interface {
    Destroy()
    ConnectURL() string  // "Main" service URL in service-specific format
    URLs() map[string]string // Should at least contain "main". May contain extra
    Log() io.Reader
}

type ContainerImage struct {
  Name string
  ImageArguments []string
  Inspector interface {
    // Inspect Container and wait for it to be ready
    WaitForReady(Container)
  }
}

type Monitor interface {
    IsAlive() bool
}

type Runner interface {
   GetMonitor() Monitor
   Deploy(ContainerImage) (Container, error)
}

// Set from init
var Impl Runner

type RegexStager *regexp.Regexp // Implementing ContainerImage.Inspector

// Usage:
container, err := dockertest.Deploy(dockertest.MySQL56)
defer container.Destroy()

db, err := sql.Open(container.ConnectURL())
aux, err := net.Dial("tcp", container.URLs()["aux"])
```

**Comment by rawler** [comment]
Since I am uncertain about advanced uses of Docker (docker swarm, compose, etc) I will try to focus on the ContainerImage for the next day.

**Comment by arekkas** [comment]
Yes, don't bother with docker swarm for now. It's just an advanced case for the future.

The code snippet looks cool. Thank you so much for dedicating some time 👍 👍 👍 👍

**Comment by rawler** [comment]
A first draft is now available in https://github.com/rawler/dockertest/commits/v3

There have been some slight changes from the proposed API above (naming for one), but the general idea stands.

It still needs some cleanup, polish and wider testing. Also, I still haven't had time for the `Runner` interface abstraction. Will try to find time for those things tomorrow, and submit a pull-request.

Please have a quick skim-through when you have the time, so everything is in order.

**Comment by arekkas** [comment]
I dug through the code and it looks really cool. I haven't tried booting images with it yet but it looks right. I will look at this in more detail tomorrow. Thanks for your hard work!

One thing: You could replace https://github.com/rawler/dockertest/blob/v3/mysql.go#L33-L73 with a factory `NewMySQLTemplate(flavor, version)` - or more generally replace all static template exports with factories?

**Comment by rawler** [comment]
Hmm. I am a bit undecided about factories. On the extreme, I guess one could build a general factory `LoadTemplate(name, version string)`

Pros:
  - Minimizes the public API
  - Allows the user to easily try other versions than forseen
Cons:
  - Records no information's of versions known to work
  - Slightly obfuscates the fact that the user can pass his own specification, launching completely unforeseen services.

I consider a comprise; giving the Specification a builders interface, so you can `Deploy(MySQL5.Version("5.5"))

What do you think?

**Comment by arekkas** [comment]
> I consider a compromise; giving the Specification a builders interface, so you can `Deploy(MySQL5.Version("5.5"))`

Agreed. We could do something like:

```
var supportedVersions = map[string]bool{
    "5.0",
    "5.5",
    //...
}

struct MySQL struct {}

func (m *MySQL) Version(version string) {
    if _, ok := supportedVersions[version]; !ok {
        // warning
    }
}
```

**Comment by rawler** [comment]
Would be nice, but I'm afraid I'm starting to run out of my allotted time.

I will make a PR of the things I have so far, it should be in decent shape, I believe. There are a few things left, which will be detailed in the PR.

**Comment by arekkas** [comment]
Perfect, I will take over then. Thanks so much for contributing! Don't get frustrated on long response times next week, I'm on vacation :)

**Comment by arekkas** [comment]
Please choose https://github.com/ory-am/dockertest/tree/v3 as base branch
