### ISSUE TITLE
Why is cmd/exec being used to run Docker?

### ISSUE THREAD

**Issue by iamthemuffinman** [ory-am/dockertest#50]
Instead of the Docker client? Just curious.

**Comment by arekkas** [comment]
see https://github.com/ory-am/dockertest/issues/11

**Comment by arekkas** [comment]
hey, this was fixed now, check out #66

**Comment by iamthemuffinman** [comment]
@arekkas Awesome! Thanks for keeping me in mind!

**Comment by arekkas** [comment]
you're welcome. Sorry that it took so long

**Comment by iamthemuffinman** [comment]
No problem at all. That PR looks squeaky clean. Good work!

**Comment by iamthemuffinman** [comment]
Also, most authors/maintainers don't think to come back and comment on old issues letting them know their original problem/question has been solved. Kudos to you on that.

**Comment by arekkas** [comment]
Thanks!
