### ISSUE TITLE
Cassandra

### ISSUE THREAD

**Issue by jerome-laforge** [ory-am/dockertest#54]
Hello,
Does it planned the support of cassandra?
Thx in adv

**Comment by arekkas** [comment]
no, but feel free to create a PR

**Comment by mfycheng** [comment]
@jerome-laforge It now supports cassandra.

**Comment by jerome-laforge** [comment]
Many thx, for this.
I have implemented my owned cassandra support but I haven't enough time to create PR.

But your implementation seems good to me except for I want add optional environment (plz see: https://gist.github.com/jerome-laforge/9333dedb9b7dd70ea2414fb6585c1463#file-stuff_test-go-L5).
could you add into your func prototype this: (plz see https://gist.github.com/jerome-laforge/9333dedb9b7dd70ea2414fb6585c1463#file-cassandra-go-L18)

Thx again.

**Comment by jerome-laforge** [comment]
And I forget, could you not publish all exposed port by removed -P (like https://gist.github.com/jerome-laforge/9333dedb9b7dd70ea2414fb6585c1463#file-cassandra-go-L18)

Thx again
