### ISSUE TITLE
Is this still in active development?

### ISSUE THREAD

**Issue by germanvazquez-rfk** [ory-am/dockertest#61]
I am planning to use dockertest to code my test base for my new golang microservices.
This is a great tool for that.
Besides, are you planning to put kafka into dockertest?

**Comment by arekkas** [comment]
Yes, dockertest is used in almost all of our projects and actively maintained. Version 3.0.0 however might still need some time.

Kafka is not on my list but feel free to contribute, as so many have before! :)

**Comment by arekkas** [comment]
I will close this issue, if you feel the need, create a new issue for Kafka - or an PR :)

**Comment by germanvazquez-rfk** [comment]
Excellent, I will, I will :)
